@startuml
start

repeat
  :Ввод данных о месте и сеансе;
  if (Все поля заполнены?) then (Да)
    :Проверить возрастное ограничение фильма;
    if (Возраст посетителя >= ограничению?) then (Да)
      if (Есть свободные места?) then (Да)
        :Продажа билета;
        :Сохранить данные в базе;
        :Печать/отправка билета;
        break
      else (Нет)
        :Сообщение: Место занято;
      endif
    else (Нет)
      :Сообщение: Возрастное ограничение;
    endif
  else (Нет)
    :Сообщить об ошибке ввода;
  endif
repeat while (Повторить ввод) is (Да)
stop
@enduml