@startuml
left to right direction
actor Посетитель
actor Админ

Посетитель -- (Просмотр расписания)
Посетитель -- (Бронирование билетов)
Посетитель -- (Продажа билетов)
Посетитель --(Отмена бронирования)

(Бронирование билетов) -- (Ввод данных покупателя) : <<include>>
(Продажа билетов) -- (Ввод данных покупателя) : <<include>>
(Отмена бронирования) -- (Ввод данных покупателя) : <<include>>

Админ -- (Редактирование расписания)
Админ -- (Формирование расписания)

(Редактирование расписания) -- (Регистрация админа) : <<include>>
(Формирование расписания) -- (Регистрация админа) : <<include>>
@enduml
