@startuml
left to right direction
actor Посетитель
actor Админ

Посетитель -- (Просмотр расписания)
Посетитель -- (Бронирование билетов)
Посетитель --(Отмена бронирования)

(Бронирование билетов) -- (Ввод данных покупателя) : <<include>>
(Отмена бронирования) -- (Ввод данных покупателя) : <<include>>
(Просмотр расписания) -- (Ввод данных покупателя) : <<include>>

Админ -- (Редактирование расписания)
Админ -- (Формирование расписания)
Админ -- (Просмотр расписания)
Админ -- (Просмотр посетителей)

(Редактирование расписания) -- (Регистрация админа) : <<include>>
(Формирование расписания) -- (Регистрация админа) : <<include>>
(Просмотр расписания) -- (Регистрация админа) : <<include>>
(Просмотр посетителей) -- (Регистрация админа) : <<include>>
@enduml
